// <auto-generated />
namespace ChhayaNirh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddRentTypeToPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRentTypeToPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202509111810172_AddRentTypeToPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
